#!/usr/bin/env bash

declare -A dependencies=(
	[bash]='bash|version 5\.'
	[direnv]='direnv|^2\.'
	[gnu-sed]='gsed|GNU gsed.*\4.'
	[dialog]='dialog|Version: 1\.'
	[coreutils]='truncate|coreutils.*9\.'
)

if [[ 'Darwin' == $(uname -s) ]]; then
  if [[ ! -x /usr/local/bin/brew ]]; then
    echo "No fun without brew! Install it then try again."
    exit 1
  fi

  echo "Check and brew install missing proenv deps:"
  echo
  for pkg in "${!dependencies[@]}"; do
    pkg_exec="/usr/local/bin/$(echo ${dependencies[$pkg]} | cut -d'|' -f1)"
    pkg_patt="$(echo ${dependencies[$pkg]} | cut -d'|' -f2)"
    prefix="\tbrew ${pkg}                  "
    if $pkg_exec --version | grep -e "$pkg_patt"; then
      echo -e "${prefix:: 18}\t\tPRESENT: installed"
    else
      echo -e "${prefix:: 18}\t\tMISSING: installing"
      brew install ${pkg}
    fi
  done
fi
