#!/usr/bin/env bash

dependencies=(bash direnv gnu-sed dialog coreutils)

if [[ 'Darwin' == $(uname -s) ]]; then
  if [[ ! -x /usr/local/bin/brew ]]; then
    echo "No fun without brew! Install it then try again."
    exit 1
  fi

  echo "Check and brew install missing proenv deps:"
  echo
  for pkg in "${dependencies[@]}"; do
      prefix="\tbrew ${pkg}                  "
    if brew list ${pkg} &>/dev/null; then
      echo -e "${prefix:: 18}\t\tPRESENT: installed"
    else
      echo -e "${prefix:: 18}\t\tMISSING: installing"
      brew install ${pkg}
    fi
  done
fi
